### PR TITLE
Added my Vision of how an Alt Manager could look like

### PR DESCRIPTION
**Pull request by PrincessAkira**
- Added my Vision of a AltManager
- Please change the Background Wallpaper, just added it for Visualization Purposes

`Preview:`
image

### CODE REVIEW

**Comment by 1zun4** [comment]
Thank you for your effort, but this does not fit with our design concept. But as long we're not done with our own alt manager, we should use it. This is better than what I've done for testing purposes. Might make your own theme in the future, when nextgen is somewhat done.

**Comment by PrincessAkira** [comment]
You just need to tell me what you want in there, like colours and such.
Worked out of the Blue there, but if you change the Background to something Blue it will actually fit in there imho.

**Comment by 1zun4** [comment]
No. We have a completely different design concept, which can be done ourself, but still has to be designed from our designer.

**Comment by PrincessAkira** [comment]
Aight.
if you need help at Graphics Design stuff or frontend or smth you know where to find me

**Pull request merged**
