### PR TITLE
Made ClickGui dragable/scrollable to have infinite space

### PR DESCRIPTION
**Pull request by tiagodinis33**
Today i discovered a bug that you could cause a overflow if you drag a category out of the screen and scroll as in this PR #6,
So i decided to use it for my advantage, by making it dragable/scrollable, so you have infinite space to organize your categories!
This is extremely useful if you have a small screen, because liquidbounce has a lot of options and features

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
Does it make the black background of the clickgui also follow the screen instead of being left behind?

**Comment by tiagodinis33** [comment]
yes
I made that fix

**Comment by tiagodinis33** [comment]
I'm working on making it draggable, like, you click and drag the backgrround and it moves the entire clickgui with your mouse

**Comment by tiagodinis33** [comment]
Unfortunely, the maven repo that's was hosting the minecraft libraries is off, and idk if it when it will return back,
so, this PR will be a bit inactive, because i cant test my changes

**Comment by tiagodinis33** [comment]
The problem was fixed and now i'll work on this

**Comment by 1zun4** [comment]
Somehow I'm not really able to make it work. The background does not move when I try to drag it.

**Comment by 1zun4** [comment]
https://user-images.githubusercontent.com/69533520/126043604-323b3865-b48d-4aa7-ad4e-fb28820e0f64.mp4

**Comment by tiagodinis33** [comment]
is was working on my browser wtf

**Comment by tiagodinis33** [comment]
may be its an missing functionality in liquidbounce,
because it works on my browser

**Comment by BobIsMyManager** [comment]
U were testing in your browser?

**Comment by 1zun4** [comment]
I tried it in the browser too using `npm run dev` and it did not work.

**Comment by tiagodinis33** [comment]
I give up XD

**Pull request closed without merging**
