### PR TITLE
fixed y overflow in click-gui

### PR DESCRIPTION
**Pull request by tiagodinis33**
If you moved a category to out of the screen, you could scroll the clickgui
image
image

### CODE REVIEW

**Comment by mems01** [comment]
Is it me, or that's a feature?

**Comment by tiagodinis33** [comment]
i dont think so, but if it was supposed to be a feature, then i can change the title of this PR to "fix background when scrolling clickgui"

**Comment by mems01** [comment]
I believe the whole thing is a feature. In case you don't have enough space, just drag the category down to a comfortable spot.

**Comment by tiagodinis33** [comment]
Hmm,sounds cool, i'll close this PR and make other to fix the backgorund bug

**Pull request closed without merging**
